import type {
  Track,
  Artist,
  LiquidityPool,
  Playlist,
  SongCredit,
  ArtistVault,
  LiquidityMix,
  RecentlyPlayed,
} from "./types"

export const mockTracks: Track[] = [
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "Luna Eclipse",
    artistId: "artist-1",
    album: "Nocturnal Vibes",
    duration: 245,
    coverUrl: "/abstract-purple-album-cover.jpg",
    audioUrl: "",
    mood: "chill",
    genre: "Electronic",
    isNFT: true,
    nftPrice: 0.5,
  },
  {
    id: "2",
    title: "Electric Pulse",
    artist: "Neon Waves",
    artistId: "artist-2",
    album: "Digital Horizons",
    duration: 198,
    coverUrl: "/neon-blue-album-cover.jpg",
    audioUrl: "",
    mood: "energetic",
    genre: "Synthwave",
    isNFT: false,
  },
  {
    id: "3",
    title: "Deep Focus",
    artist: "Ambient Collective",
    artistId: "artist-3",
    album: "Concentration",
    duration: 312,
    coverUrl: "/minimal-gradient-album.jpg",
    audioUrl: "",
    mood: "focus",
    genre: "Ambient",
    isNFT: false,
  },
  {
    id: "4",
    title: "Crypto Anthem",
    artist: "BlockBeats",
    artistId: "artist-4",
    album: "Decentralized",
    duration: 223,
    coverUrl: "/futuristic-crypto-album.jpg",
    audioUrl: "",
    mood: "energetic",
    genre: "Electronic",
    isNFT: true,
    nftPrice: 1.2,
  },
  {
    id: "5",
    title: "Sunset Boulevard",
    artist: "Luna Eclipse",
    artistId: "artist-1",
    album: "Golden Hour",
    duration: 267,
    coverUrl: "/sunset-gradient-album.jpg",
    audioUrl: "",
    mood: "happy",
    genre: "Indie Pop",
    isNFT: false,
  },
  {
    id: "6",
    title: "Blockchain Symphony",
    artist: "Crypto Orchestra",
    artistId: "artist-5",
    album: "Web3 Classics",
    duration: 289,
    coverUrl: "/digital-symphony-album.jpg",
    audioUrl: "",
    mood: "focus",
    genre: "Classical Electronic",
    isNFT: true,
    nftPrice: 0.8,
  },
]

export const mockArtists: Artist[] = [
  {
    id: "artist-1",
    name: "Luna Eclipse",
    imageUrl: "/female-artist-portrait-purple.jpg",
    followers: 125000,
    verified: true,
    bio: "Electronic music producer exploring the intersection of sound and blockchain.",
    tokenSymbol: "LUNA",
    tokenPrice: 2.45,
  },
  {
    id: "artist-2",
    name: "Neon Waves",
    imageUrl: "/synthwave-artist-neon.jpg",
    followers: 89000,
    verified: true,
    bio: "Synthwave artist bringing 80s vibes to the metaverse.",
    tokenSymbol: "NEON",
    tokenPrice: 1.87,
  },
  {
    id: "artist-3",
    name: "Ambient Collective",
    imageUrl: "/ambient-music-collective.jpg",
    followers: 67000,
    verified: false,
    bio: "Creating soundscapes for focus and relaxation.",
    tokenSymbol: "AMBI",
    tokenPrice: 0.92,
  },
  {
    id: "artist-4",
    name: "BlockBeats",
    imageUrl: "/crypto-dj-futuristic.jpg",
    followers: 203000,
    verified: true,
    bio: "Pioneering crypto-native music experiences.",
    tokenSymbol: "BEAT",
    tokenPrice: 3.21,
  },
  {
    id: "artist-5",
    name: "Crypto Orchestra",
    imageUrl: "/digital-orchestra-conductor.jpg",
    followers: 45000,
    verified: true,
    bio: "Merging classical composition with blockchain technology.",
    tokenSymbol: "ORCH",
    tokenPrice: 1.56,
  },
  {
    id: "artist-6",
    name: "Crypto Oracle",
    imageUrl: "/oracle-artist.jpg",
    followers: 30000,
    verified: true,
    bio: "Featured artist on BlockBeats' tracks.",
    tokenSymbol: "ORCL",
    tokenPrice: 2.15,
  },
]

export const mockLiquidityPools: LiquidityPool[] = [
  {
    id: "pool-1",
    artistId: "artist-1",
    artistName: "Luna Eclipse",
    artistImage: "/female-artist-portrait-purple.jpg",
    tokenSymbol: "LUNA",
    apr: 24.5,
    totalStaked: 1250000,
    userStaked: 5000,
    userStake: 5000,
    userRewards: 125.50,
    totalStakers: 2847,
    tokenPrice: 2.45,
    volume24h: 89000,
    volumeChange24h: 12.5,
    description: "Support Luna Eclipse and earn rewards from streaming royalties",
  },
  {
    id: "pool-2",
    artistId: "artist-4",
    artistName: "BlockBeats",
    artistImage: "/crypto-dj-futuristic.jpg",
    tokenSymbol: "BEAT",
    apr: 32.8,
    totalStaked: 2100000,
    userStaked: 10000,
    userStake: 10000,
    userRewards: 328.00,
    totalStakers: 4521,
    tokenPrice: 3.21,
    volume24h: 156000,
    volumeChange24h: 8.3,
    description: "Stake BEAT tokens and share in NFT sales and concert revenue",
  },
  {
    id: "pool-3",
    artistId: "artist-2",
    artistName: "Neon Waves",
    artistImage: "/synthwave-artist-neon.jpg",
    tokenSymbol: "NEON",
    apr: 18.3,
    totalStaked: 890000,
    userStaked: 2500,
    userStake: 2500,
    userRewards: 45.75,
    totalStakers: 1823,
    tokenPrice: 1.87,
    volume24h: 67000,
    volumeChange24h: -2.1,
    description: "Earn from Neon Waves' growing catalog and merchandise sales",
  },
  {
    id: "pool-4",
    artistId: "artist-5",
    artistName: "Crypto Orchestra",
    artistImage: "/digital-orchestra-conductor.jpg",
    tokenSymbol: "ORCH",
    apr: 15.7,
    totalStaked: 560000,
    userStaked: 0,
    userStake: 0,
    userRewards: 0,
    totalStakers: 1247,
    tokenPrice: 1.56,
    volume24h: 34000,
    volumeChange24h: 5.7,
    description: "Support classical music innovation on the blockchain",
  },
]

export const mockPlaylists: Playlist[] = [
  {
    id: "playlist-1",
    name: "Crypto Vibes",
    description: "The best blockchain-native tracks",
    coverUrl: "/crypto-playlist-cover.jpg",
    tracks: [mockTracks[3], mockTracks[5], mockTracks[0]],
    isPublic: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "playlist-2",
    name: "Focus Flow",
    description: "Deep concentration music",
    coverUrl: "/focus-playlist-minimal.jpg",
    tracks: [mockTracks[2], mockTracks[5]],
    isPublic: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "playlist-3",
    name: "Night Drive",
    description: "Synthwave and chill beats",
    coverUrl: "/night-drive-neon.jpg",
    tracks: [mockTracks[1], mockTracks[4], mockTracks[0]],
    isPublic: true,
    createdAt: new Date("2024-02-10"),
  },
]

export const mockCredits: Record<string, SongCredit[]> = {
  "1": [
    { role: "Songwriter", name: "Luna Eclipse", id: "artist-1" },
    { role: "Producer", name: "Alex Synthwave", id: "producer-1" },
    { role: "Mixing Engineer", name: "Sarah Chen", id: "engineer-1" },
    { role: "Label", name: "Crypto Records", id: "label-1" },
  ],
  "2": [
    { role: "Songwriter", name: "Neon Waves", id: "artist-2" },
    { role: "Producer", name: "Neon Waves", id: "artist-2" },
    { role: "Mastering", name: "Digital Masters Studio", id: "studio-1" },
  ],
  "3": [
    { role: "Composer", name: "Ambient Collective", id: "artist-3" },
    { role: "Sound Design", name: "Echo Labs", id: "studio-2" },
  ],
  "4": [
    { role: "Songwriter", name: "BlockBeats", id: "artist-4" },
    { role: "Producer", name: "BlockBeats", id: "artist-4" },
    { role: "Featured Artist", name: "Crypto Oracle", id: "artist-6" },
    { role: "Label", name: "Web3 Music Group", id: "label-2" },
  ],
}

export const mockArtistVaults: Record<string, ArtistVault> = {
  "artist-1": {
    id: "vault-1",
    artistId: "artist-1",
    artistName: "Luna Eclipse",
    tokenSymbol: "LUNA",
    apy: 24.5,
    totalLiquidity: 1250000,
    userDeposited: 5000,
    yieldHistory: [
      { date: "Jan", yield: 22.1 },
      { date: "Feb", yield: 23.5 },
      { date: "Mar", yield: 24.8 },
      { date: "Apr", yield: 24.5 },
    ],
  },
  "artist-2": {
    id: "vault-2",
    artistId: "artist-2",
    artistName: "Neon Waves",
    tokenSymbol: "NEON",
    apy: 18.3,
    totalLiquidity: 890000,
    userDeposited: 2500,
    yieldHistory: [
      { date: "Jan", yield: 16.8 },
      { date: "Feb", yield: 17.9 },
      { date: "Mar", yield: 18.5 },
      { date: "Apr", yield: 18.3 },
    ],
  },
  "artist-4": {
    id: "vault-4",
    artistId: "artist-4",
    artistName: "BlockBeats",
    tokenSymbol: "BEAT",
    apy: 32.8,
    totalLiquidity: 2100000,
    userDeposited: 10000,
    yieldHistory: [
      { date: "Jan", yield: 29.5 },
      { date: "Feb", yield: 31.2 },
      { date: "Mar", yield: 33.1 },
      { date: "Apr", yield: 32.8 },
    ],
  },
}

export const mockLiquidityMixes: LiquidityMix[] = [
  {
    id: "mix-1",
    title: "Liquidity Mix 01",
    coverUrl: "/abstract-purple-album-cover.jpg",
    artists: "Luna Eclipse, Neon Waves, BlockBeats",
    description: "Top performing artist tokens with high APR",
    totalValue: 125000,
    apr: 28.5,
  },
  {
    id: "mix-2",
    title: "Liquidity Mix 02",
    coverUrl: "/neon-blue-album-cover.jpg",
    artists: "BlockBeats, Crypto Orchestra, Ambient Collective",
    description: "Diversified portfolio of music NFTs",
    totalValue: 89000,
    apr: 22.3,
  },
  {
    id: "mix-3",
    title: "Liquidity Mix 03",
    coverUrl: "/minimal-gradient-album.jpg",
    artists: "Ambient Collective, Luna Eclipse",
    description: "Chill vibes with steady yields",
    totalValue: 67000,
    apr: 19.8,
  },
  {
    id: "mix-4",
    title: "Liquidity Mix 04",
    coverUrl: "/futuristic-crypto-album.jpg",
    artists: "Neon Waves, BlockBeats",
    description: "High-energy tracks with premium returns",
    totalValue: 103000,
    apr: 31.2,
  },
  {
    id: "mix-5",
    title: "Liquidity Mix 05",
    coverUrl: "/sunset-gradient-album.jpg",
    artists: "Luna Eclipse, Crypto Orchestra",
    description: "Curated selection of verified artists",
    totalValue: 94000,
    apr: 25.7,
  },
]

export const mockRecentlyPlayed: RecentlyPlayed[] = [
  {
    id: "recent-1",
    trackId: "1",
    title: "Midnight Dreams",
    artist: "Luna Eclipse",
    coverUrl: "/abstract-purple-album-cover.jpg",
    playedAt: new Date(Date.now() - 1000 * 60 * 30), // 30 mins ago
    isStaked: true,
    stakedAmount: 5000,
  },
  {
    id: "recent-2",
    trackId: "4",
    title: "Crypto Anthem",
    artist: "BlockBeats",
    coverUrl: "/futuristic-crypto-album.jpg",
    playedAt: new Date(Date.now() - 1000 * 60 * 60 * 2), // 2 hours ago
    isStaked: true,
    stakedAmount: 10000,
  },
  {
    id: "recent-3",
    trackId: "2",
    title: "Electric Pulse",
    artist: "Neon Waves",
    coverUrl: "/neon-blue-album-cover.jpg",
    playedAt: new Date(Date.now() - 1000 * 60 * 60 * 5), // 5 hours ago
    isStaked: false,
  },
  {
    id: "recent-4",
    trackId: "5",
    title: "Sunset Boulevard",
    artist: "Luna Eclipse",
    coverUrl: "/sunset-gradient-album.jpg",
    playedAt: new Date(Date.now() - 1000 * 60 * 60 * 12), // 12 hours ago
    isStaked: false,
  },
  {
    id: "recent-5",
    trackId: "6",
    title: "Blockchain Symphony",
    artist: "Crypto Orchestra",
    coverUrl: "/digital-symphony-album.jpg",
    playedAt: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 day ago
    isStaked: true,
    stakedAmount: 2500,
  },
  {
    id: "recent-6",
    trackId: "3",
    title: "Deep Focus",
    artist: "Ambient Collective",
    coverUrl: "/minimal-gradient-album.jpg",
    playedAt: new Date(Date.now() - 1000 * 60 * 60 * 36), // 1.5 days ago
    isStaked: false,
  },
]
